name: anime_slayer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logger: ^2.2.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  hooks_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  go_router: ^14.0.0
  equatable: ^2.0.5
  pretty_dio_logger: ^1.3.1
  video_player: ^2.8.6
  responsive_grid_list: ^1.4.0
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
